name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # Adjust this to your Go version

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Run tests
      - name: Run tests
        run: go test -v ./...

      # Load 1Password secrets
      - name: Install 1Password CLI
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load Production Secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          JWT_SECRET: op://storage-secrets-prod/production-env/JWT_SECRET
          POSTGRES_PASSWORD: op://storage-secrets-prod/production-env/POSTGRES_PASSWORD
          AWS_ACCESS_KEY_ID: op://storage-secrets-prod/production-env/AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: op://storage-secrets-prod/production-env/AWS_SECRET_ACCESS_KEY
          AWS_REGION: op://storage-secrets-prod/production-env/AWS_REGION
          S3_BUCKET: op://storage-secrets-prod/production-env/S3_BUCKET

      # Build the application
      - name: Build
        run: go build -v ./...

      # Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm i -g vercel
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
